### ISSUE TITLE
Missing api folder

### ISSUE THREAD

**Issue by iamthenewking** [Startup-Landing/agency-creative#1]
hi I don't see scr/pages/api folder containing the mail integration

**Comment by neamatmim** [comment]
Hi,
please go to https://github.com/Startup-Landing/agency-minimal/tree/master/agency-minimal-next/src/pages/api and copy the content from there.

**Comment by iamthenewking** [comment]
> Hi,
> please go to https://github.com/Startup-Landing/agency-minimal/tree/master/agency-minimal-next/src/pages/api and copy the content from there.

thanks neamitmin
